# Generated by Django 6.0.3 on 2026-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0002_crawlrawdata_record_type_crawlrawdata_unique_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawltarget",
            name="crawl_interval_minutes",
            field=models.PositiveIntegerField(
                default=60, help_text="이 target을 다시 수집할 최소 간격(분)"
            ),
        ),
        migrations.AddField(
            model_name="crawltarget",
            name="priority",
            field=models.PositiveIntegerField(
                default=1, help_text="숫자가 클수록 우선 수집"
            ),
        ),
    ]
