# Generated by Django 6.0.3 on 2026-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0003_crawltarget_crawl_interval_minutes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crawltarget",
            options={
                "ordering": ["-priority", "site", "target_type", "-created_at"],
                "verbose_name": "크롤링 대상",
                "verbose_name_plural": "크롤링 대상 목록",
            },
        ),
        migrations.AlterField(
            model_name="crawlrawdata",
            name="unique_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
