"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
from pathlib import Path
import os

# =========================================================
# 기본 경로 설정
# =========================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# .env 읽기
# =========================================================
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# =========================================================
# 보안 / 실행 환경
# =========================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="dev-secret-key")
# [★수정]
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# [★수정]
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # DRF
    "rest_framework",
    # apps
    "apps.accounts",
    "apps.products",
    "apps.reviews",
    "apps.interactions",
    "apps.ai_gateway",
    "apps.crawling",
    "pgvector.django",
    "storages",
    "django_prometheus",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 프로젝트 공통
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DB_NAME = env("DB_NAME", default="product_review_db")
DB_USER = env("DB_USER", default="product_review_user")
DB_PASSWORD = env("DB_PASSWORD", default="product_review_password")
DB_HOST = env("DB_HOST", default="db")
DB_PORT = env("DB_PORT", default="5432")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 3,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # 비로그인 사용자
        "rest_framework.throttling.UserRateThrottle",  # 로그인 사용자
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/day",  # 비로그인 유저는 하루 10번
        "user": "100/day",  # 로그인 유저는 하루 100번
        "ai_analysis": "5/min",  # 특정 AI 분석 API는 분당 5번으로 제한
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

STORAGES = {
    "default": {
        "BACKEND": "mysite.storage.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "mysite.storage.StaticStorage",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

AUTH_USER_MODEL = "accounts.User"

# S3를 사용할 경우 이부분은 주석처리 합니다.
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")

AWS_DEFAULT_ACL = None

# S3를 사용할 경우 이부분은 주석처리 합니다.
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# 순서대로 실행되므로 순서를 반드시 맞춰주세요.
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-northeast-2")
AWS_STORAGE_BUCKET_NAME_STATIC = os.getenv("AWS_STORAGE_BUCKET_NAME_STATIC")
AWS_STORAGE_BUCKET_NAME_MEDIA = os.getenv("AWS_STORAGE_BUCKET_NAME_MEDIA")

STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME_STATIC}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/"
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME_MEDIA}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"

# =========================================================
# FastAPI 서버 주소
# docker-compose 내부 통신 기준 기본값
# =========================================================
FASTAPI_BASE_URL = env("FASTAPI_BASE_URL", default="http://fastapi:8001")
# =========================================================
# [추가] Celery + Redis 설정
# =========================================================

# [추가] Redis 주소
# docker-compose 사용 시 보통 redis://redis:6379/0
# 로컬 직접 실행 시 redis://127.0.0.1:6379/0
# =========================================================
# Celery + Redis
# docker-compose 내부 통신 기준 기본값
# =========================================================
REDIS_URL = env("REDIS_URL", default="redis://redis:6379/0")
# [추가] Celery broker / backend
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# [추가] 직렬화 포맷
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# [추가] 시간대
CELERY_TIMEZONE = "Asia/Seoul"

# [추가] 작업 결과 만료 시간(1시간)
CELERY_RESULT_EXPIRES = 3600

# [추가] worker가 한 번에 너무 많은 작업을 오래 붙잡지 않도록 설정
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# [추가] 작업 시작 상태 추적
CELERY_TASK_TRACK_STARTED = True

# [추가] 긴 작업 안정성용
CELERY_TASK_TIME_LIMIT = 60 * 10
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 8

# [추가] 테스트/개발 중 eager 모드 쓰고 싶으면 환경변수로 제어 가능
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = True

CORS_ALLOWED_ORIGINS = [
    "https://your-domain.com",
    "http://localhost:8000",  # 개발 환경
]
CORS_ALLOW_CREDENTIALS = True

# =========================================================
# Default primary key field type
# =========================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
