# Generated by Django 6.0.3 on 2026-04-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_gateway", "0001_initial"),
        ("reviews", "0002_alter_review_options_alter_reviewai_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("STARTED", "진행중"),
                            ("SUCCESS", "완료"),
                            ("FAILURE", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="upskyy/e5-small-korean", max_length=100),
                ),
                ("similarity_threshold", models.FloatField(default=0.45)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analysis_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_tasks",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
