# Generated by Django 6.0.3 on 2026-03-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productai"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductAI",
            new_name="ProductIMG",
        ),
    ]
