# Generated by Django 6.0.3 on 2026-03-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_productai_productimg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductIMG",
            new_name="ProductAI",
        ),
    ]
